import type { PantryItem, Recipe, WeeklyMenu, ShoppingItem } from '@/types';

export const pantryItems: PantryItem[] = [
  { id: 'p1',  name: 'Eggs',           quantity: 12,  unit: 'units', category: 'dairy',   location: 'fridge',  expiresAt: '2026-03-28' },
  { id: 'p2',  name: 'Chicken breast', quantity: 600, unit: 'g',     category: 'meat',    location: 'fridge',  expiresAt: '2026-03-22' },
  { id: 'p3',  name: 'Pasta',          quantity: 500, unit: 'g',     category: 'pantry',  location: 'pantry' },
  { id: 'p4',  name: 'Tomato sauce',   quantity: 2,   unit: 'cans',  category: 'pantry',  location: 'pantry' },
  { id: 'p5',  name: 'Olive oil',      quantity: 1,   unit: 'bottle',category: 'pantry',  location: 'pantry' },
  { id: 'p6',  name: 'Onion',          quantity: 3,   unit: 'units', category: 'produce', location: 'pantry',  expiresAt: '2026-04-01' },
  { id: 'p7',  name: 'Garlic',         quantity: 1,   unit: 'head',  category: 'produce', location: 'pantry' },
  { id: 'p8',  name: 'Spinach',        quantity: 200, unit: 'g',     category: 'produce', location: 'fridge',  expiresAt: '2026-03-23' },
  { id: 'p9',  name: 'Greek yogurt',   quantity: 500, unit: 'g',     category: 'dairy',   location: 'fridge',  expiresAt: '2026-03-25' },
  { id: 'p10', name: 'Oats',           quantity: 800, unit: 'g',     category: 'pantry',  location: 'pantry' },
  { id: 'p11', name: 'Banana',         quantity: 5,   unit: 'units', category: 'produce', location: 'pantry',  expiresAt: '2026-03-24' },
  { id: 'p12', name: 'Lentils',        quantity: 400, unit: 'g',     category: 'pantry',  location: 'pantry' },
  { id: 'p13', name: 'Peas',           quantity: 300, unit: 'g',     category: 'frozen',  location: 'freezer' },
  { id: 'p14', name: 'Salmon fillet',  quantity: 400, unit: 'g',     category: 'meat',    location: 'freezer', expiresAt: '2026-04-15' },
  { id: 'p15', name: 'Mozzarella',     quantity: 125, unit: 'g',     category: 'dairy',   location: 'fridge',  expiresAt: '2026-03-21' },
];

export const recipes: Recipe[] = [
  {
    id: 'r1',
    name: 'Scrambled eggs with spinach',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    description: 'Quick and nutritious breakfast with eggs and fresh spinach.',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    kcal: 280,
    tags: ['breakfast', 'quick', 'vegetarian'],
    ingredients: [
      { pantryItemId: 'p1', name: 'Eggs',      quantity: 4,  unit: 'units' },
      { pantryItemId: 'p8', name: 'Spinach',   quantity: 80, unit: 'g' },
      { pantryItemId: 'p5', name: 'Olive oil', quantity: 1,  unit: 'tbsp' },
    ],
    steps: [
      'Whisk eggs in a bowl and season with salt and pepper.',
      'Heat olive oil in a pan over medium heat.',
      'Add spinach and sauté until wilted, about 2 minutes.',
      'Pour in the eggs and stir gently until cooked through.',
    ],
  },
  {
    id: 'r2',
    name: 'Banana oat porridge',
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&q=80',
    description: 'Creamy oat porridge topped with sliced banana.',
    prepTime: 2,
    cookTime: 8,
    servings: 1,
    kcal: 340,
    tags: ['breakfast', 'quick', 'vegan'],
    ingredients: [
      { pantryItemId: 'p10', name: 'Oats',          quantity: 80,  unit: 'g' },
      { pantryItemId: 'p11', name: 'Banana',         quantity: 1,   unit: 'unit' },
      {                      name: 'Milk or oat milk', quantity: 200, unit: 'ml' },
    ],
    steps: [
      'Combine oats and milk in a saucepan.',
      'Cook over medium heat, stirring, for 5–7 minutes until thick.',
      'Pour into a bowl and top with sliced banana.',
    ],
  },
  {
    id: 'r3',
    name: 'Pasta with tomato sauce',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-054e07b0e3b5?w=400&q=80',
    description: 'Classic Italian pasta with homemade tomato sauce.',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    kcal: 520,
    tags: ['dinner', 'vegetarian', 'family'],
    ingredients: [
      { pantryItemId: 'p3', name: 'Pasta',        quantity: 400, unit: 'g' },
      { pantryItemId: 'p4', name: 'Tomato sauce', quantity: 1,   unit: 'can' },
      { pantryItemId: 'p6', name: 'Onion',        quantity: 1,   unit: 'unit' },
      { pantryItemId: 'p7', name: 'Garlic',       quantity: 2,   unit: 'cloves' },
      { pantryItemId: 'p5', name: 'Olive oil',    quantity: 2,   unit: 'tbsp' },
    ],
    steps: [
      'Bring a large pot of salted water to a boil.',
      'Cook pasta according to package instructions, then drain.',
      'Dice onion and mince garlic.',
      'Sauté onion in olive oil until soft, then add garlic for 1 minute.',
      'Add tomato sauce and simmer for 10 minutes. Season to taste.',
      'Toss pasta with sauce and serve.',
    ],
  },
  {
    id: 'r4',
    name: 'Grilled chicken with lentils',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-6c2a3c9d97e5?w=400&q=80',
    description: 'Protein-packed dinner with grilled chicken breast and spiced lentils.',
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    kcal: 610,
    tags: ['dinner', 'high-protein', 'healthy'],
    ingredients: [
      { pantryItemId: 'p2',  name: 'Chicken breast', quantity: 300, unit: 'g' },
      { pantryItemId: 'p12', name: 'Lentils',        quantity: 200, unit: 'g' },
      { pantryItemId: 'p6',  name: 'Onion',          quantity: 1,   unit: 'unit' },
      { pantryItemId: 'p7',  name: 'Garlic',         quantity: 2,   unit: 'cloves' },
      { pantryItemId: 'p5',  name: 'Olive oil',      quantity: 1,   unit: 'tbsp' },
    ],
    steps: [
      'Rinse lentils and cook in salted water for 20–25 minutes until tender.',
      'Season chicken with salt, pepper, and a drizzle of olive oil.',
      'Grill chicken over medium-high heat, 6–7 minutes per side.',
      'Sauté onion and garlic in olive oil until golden.',
      'Add drained lentils to the pan, season and stir to combine.',
      'Serve chicken sliced over the lentils.',
    ],
  },
  {
    id: 'r5',
    name: 'Greek yogurt bowl',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80',
    description: 'Simple and refreshing bowl with yogurt, banana and honey.',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    kcal: 210,
    tags: ['breakfast', 'lunch', 'quick', 'vegetarian'],
    ingredients: [
      { pantryItemId: 'p9',  name: 'Greek yogurt', quantity: 200, unit: 'g' },
      { pantryItemId: 'p11', name: 'Banana',        quantity: 1,   unit: 'unit' },
      {                      name: 'Honey',          quantity: 1,   unit: 'tsp' },
    ],
    steps: [
      'Spoon yogurt into a bowl.',
      'Slice banana and arrange on top.',
      'Drizzle with honey.',
    ],
  },
  {
    id: 'r6',
    name: 'Salmon with peas',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&q=80',
    description: 'Simple baked salmon served with buttered peas.',
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    kcal: 480,
    tags: ['dinner', 'healthy', 'high-protein'],
    ingredients: [
      { pantryItemId: 'p14', name: 'Salmon fillet', quantity: 400, unit: 'g' },
      { pantryItemId: 'p13', name: 'Peas',          quantity: 200, unit: 'g' },
      { pantryItemId: 'p5',  name: 'Olive oil',     quantity: 1,   unit: 'tbsp' },
    ],
    steps: [
      'Preheat oven to 200 °C.',
      'Place salmon on a lined tray, drizzle with olive oil, season.',
      'Bake for 15–18 minutes until cooked through.',
      'Cook peas in boiling salted water for 3 minutes, drain.',
      'Serve salmon alongside the peas.',
    ],
  },
];

export const weeklyMenu: WeeklyMenu = {
  id: 'wm1',
  weekStart: '2026-03-16', // Monday
  days: {
    monday:    { breakfast: { recipeId: 'r1' }, lunch: { recipeId: 'r5' }, dinner: { recipeId: 'r3' } },
    tuesday:   { breakfast: { recipeId: 'r2' }, lunch: { recipeId: null }, dinner: { recipeId: 'r4' } },
    wednesday: { breakfast: { recipeId: 'r1' }, lunch: { recipeId: 'r5' }, dinner: { recipeId: 'r6' } },
    thursday:  { breakfast: { recipeId: 'r2' }, lunch: { recipeId: null }, dinner: { recipeId: 'r3' } },
    friday:    { breakfast: { recipeId: 'r5' }, lunch: { recipeId: 'r5' }, dinner: { recipeId: 'r4' } },
    saturday:  { breakfast: { recipeId: 'r2' }, lunch: { recipeId: null }, dinner: { recipeId: null } },
    sunday:    { breakfast: { recipeId: null }, lunch: { recipeId: null }, dinner: { recipeId: null } },
  },
};

export const shoppingList: ShoppingItem[] = [
  { id: 's1', name: 'Milk',       quantity: 1,   unit: 'L',     category: 'dairy',   checked: false, recipeIds: ['r2'] },
  { id: 's2', name: 'Honey',      quantity: 1,   unit: 'jar',   category: 'pantry',  checked: false, recipeIds: ['r5'] },
  { id: 's3', name: 'Parmesan',   quantity: 100, unit: 'g',     category: 'dairy',   checked: true,  recipeIds: ['r3'] },
  { id: 's4', name: 'Bell pepper',quantity: 2,   unit: 'units', category: 'produce', checked: false, recipeIds: [] },
  { id: 's5', name: 'Tomatoes',   quantity: 4,   unit: 'units', category: 'produce', checked: false, recipeIds: ['r3'] },
  { id: 's6', name: 'Butter',     quantity: 1,   unit: 'pack',  category: 'dairy',   checked: true,  recipeIds: [] },
  { id: 's7', name: 'Rice',       quantity: 500, unit: 'g',     category: 'pantry',  checked: false, recipeIds: [] },
];
